### ISSUE TITLE
(Feature Request) World size increaser/chunk generator

### ISSUE THREAD

**Issue by YetAnotherNotHacking** [etianl/Trouser-Streak#44]
I am not very great at it, so I do not know how complicated this is.

For people that are downloading local copies of worlds (like I am currently on various servers) or people looking to purposely generating chunks to fill up the server storage

I was thinking either a progressive back and forth or a spiral out from the center or a set position, making sure no chunks are missed.

I believe that this is a feature withing ForgeHax. but ForgeHax is forge only and is outdated, last update being over 2 years ago. (and also for forge not farbic 🤮)

It would help to have some of the following settings:
Method: spiral or back and fourth (needs better name)
chunk distance: number input from 2 to 32, seeing how large the spiral should be or how much it should move back and fourth
speed: Assuming if it is using flight, it should know what speed to travel.
height: fight to fly at
setting specifically for spiral: goal distance, how haw it should spiral to before finishing, optional log out on complete?
setting for back and fourth: start x/y and end x/y, for it to make/generate

Other features might be recovering if the server is down or restarting, know to stop and restart without missing any chunks
chat feedback on progress?

IDK if this is going to be added but I love trouser streak and it is a great project, I have it starred and use it on the servers I play on regularly, I appreciate everyone that works on it, keep it up!

**Comment by etianl** [comment]
I don't know if this would even be an effective griefing method because admins go checking on suspicious players and they'd see you flying about as a bot (Trouser-Streak is designed for griefing private servers which often have no anticheat). It also sounds real complicated to write for only a few use scenarios. I do appreciate the input though, if you get any other neat ideas feel free to submit them. There is a discussions post about module ideas feel free to add any idea you come up with there 
https://github.com/etianl/Trouser-Streak/discussions/10
